set SOLUTION_DIR=%CD%
set OSG=C:\Program Files (x86)\OpenSceneGraph
set OSG_ROOT=%OSG%
set OSG_DEPS=C:\dev\svn\osg\3rdParty_vc90
set OSGEARTH=C:\Program Files (x86)\OSGEARTH
set OSG_PLUGINS_FOLDER=osgPlugins-3.0.1
set OSGEARTH_PLUGINS=%OSGEARTH%\bin\%OSG_PLUGINS_FOLDER%
set OSG_PLUGINS_DIR=%OSG%\bin\%OSG_PLUGINS_FOLDER%
set GEOS=C:\dev\svn\geos-3.2.2
set GDAL=C:\Program Files (x86)\GDAL
set PATH=%OSG%\bin;%OSGEARTH%\bin;%OSG_DEPS%\bin;%GDAL%\bin;%PATH%
